import React from "react"
import Popover from "../popover"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Popover,
  "https://www.figma.com/design/EuFu0U7gqc1koXm8ZhlOLp/%E2%9A%A1%EF%B8%8F-Components?node-id=8781%3A11148",
  {
    props: {
      up: figma.boolean("Up"),
      right: figma.boolean("Right"),
      down: figma.boolean("Down"),
      left: figma.boolean("Left"),
      image: figma.boolean("Image"),
      style: figma.enum("Style", {
        Subtle: "subtle",
        Strong: "strong",
      }),
      arrows: figma.enum("Arrows", {
        True: "true",
      }),
      imageAlignment: figma.enum("Image Alignment", {
        Top: "top",
        Bottom: "bottom",
      }),
      writingDirection: figma.enum("Writing Direction", {
        "Left-to-Right": "left-to-right",
        "Right-to-Left": "right-to-left",
      }),
    },
    example: (props) => <Popover />,
  },
)
