// @flow
// This file is auto-generated by gen-snapshot-tests.js
// Do not edit this file.  To make changes to these snapshot tests
// edit packages/wonder-blocks-button/docs.md and run `npm run gen-snapshot-tests`.
import React from "react";
import renderer from "react-test-renderer";
import Button from "./components/button.js";

describe("wonder-blocks-button", () => {
    it("example 1", () => {
        const Color = require("wonder-blocks-color").default;
        const ButtonCore = require("./components/button-core.js").default;

        const {blue, red, white, offWhite} = Color;

        const example = (
            <table style={{background: offWhite, textAlign: "center"}}>
                <thead>
                    <tr>
                        <th />
                        <th style={{width: 100}}>Default</th>
                        <th style={{width: 100}}>
                            Hovered/<br />Focused
                        </th>
                        <th style={{width: 100}}>
                            Active/<br />Pressed
                        </th>
                        <th style={{width: 100}}>Disabled</th>
                    </tr>
                </thead>
                <tbody>
                    <tr style={{height: 60, verticalAlign: "middle"}}>
                        <th>Primary</th>
                        <td>
                            <ButtonCore
                                kind="primary"
                                size="default"
                                color={blue}
                                light={false}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="primary"
                                size="default"
                                color={blue}
                                light={false}
                                hovered={true}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="primary"
                                size="default"
                                color={blue}
                                light={false}
                                hovered={false}
                                focused={false}
                                pressed={true}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="primary"
                                size="default"
                                color={blue}
                                light={false}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={true}
                            >
                                Label
                            </ButtonCore>
                        </td>
                    </tr>
                    <tr style={{height: 60, verticalAlign: "middle"}}>
                        <th>Secondary</th>
                        <td>
                            <ButtonCore
                                kind="secondary"
                                size="default"
                                color={blue}
                                light={false}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="secondary"
                                size="default"
                                color={blue}
                                light={false}
                                hovered={true}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="secondary"
                                size="default"
                                color={blue}
                                light={false}
                                hovered={false}
                                focused={false}
                                pressed={true}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="secondary"
                                size="default"
                                color={blue}
                                light={false}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={true}
                            >
                                Label
                            </ButtonCore>
                        </td>
                    </tr>
                    <tr style={{height: 60, verticalAlign: "middle"}}>
                        <th>Tertiary</th>
                        <td>
                            <ButtonCore
                                kind="tertiary"
                                size="default"
                                color={blue}
                                light={false}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="tertiary"
                                size="default"
                                color={blue}
                                light={false}
                                hovered={true}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="tertiary"
                                size="default"
                                color={blue}
                                light={false}
                                hovered={false}
                                focused={false}
                                pressed={true}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="tertiary"
                                size="default"
                                color={blue}
                                light={false}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={true}
                            >
                                Label
                            </ButtonCore>
                        </td>
                    </tr>
                </tbody>
            </table>
        );
        const tree = renderer.create(example).toJSON();
        expect(tree).toMatchSnapshot();
    });
    it("example 2", () => {
        const Color = require("wonder-blocks-color").default;
        const ButtonCore = require("./components/button-core.js").default;

        const {blue, red, white, offWhite} = Color;

        const example = (
            <table
                style={{background: blue, color: white, textAlign: "center"}}
            >
                <thead>
                    <tr>
                        <th />
                        <th style={{width: 100}}>Default</th>
                        <th style={{width: 100}}>
                            Hovered/<br />Focused
                        </th>
                        <th style={{width: 100}}>
                            Active/<br />Pressed
                        </th>
                        <th style={{width: 100}}>Disabled</th>
                    </tr>
                </thead>
                <tbody>
                    <tr style={{height: 60, verticalAlign: "middle"}}>
                        <th>Primary</th>
                        <td>
                            <ButtonCore
                                kind="primary"
                                size="default"
                                color={blue}
                                light={true}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="primary"
                                size="default"
                                color={blue}
                                light={true}
                                hovered={true}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="primary"
                                size="default"
                                color={blue}
                                light={true}
                                hovered={false}
                                focused={false}
                                pressed={true}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="primary"
                                size="default"
                                color={blue}
                                light={true}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={true}
                            >
                                Label
                            </ButtonCore>
                        </td>
                    </tr>
                    <tr style={{height: 60, verticalAlign: "middle"}}>
                        <th>Secondary</th>
                        <td>
                            <ButtonCore
                                kind="secondary"
                                size="default"
                                color={blue}
                                light={true}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="secondary"
                                size="default"
                                color={blue}
                                light={true}
                                hovered={true}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="secondary"
                                size="default"
                                color={blue}
                                light={true}
                                hovered={false}
                                focused={false}
                                pressed={true}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="secondary"
                                size="default"
                                color={blue}
                                light={true}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={true}
                            >
                                Label
                            </ButtonCore>
                        </td>
                    </tr>
                    <tr style={{height: 60, verticalAlign: "middle"}}>
                        <th>Tertiary</th>
                        <td>
                            <ButtonCore
                                kind="tertiary"
                                size="default"
                                color={blue}
                                light={true}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="tertiary"
                                size="default"
                                color={blue}
                                light={true}
                                hovered={true}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="tertiary"
                                size="default"
                                color={blue}
                                light={true}
                                hovered={false}
                                focused={false}
                                pressed={true}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="tertiary"
                                size="default"
                                color={blue}
                                light={true}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={true}
                            >
                                Label
                            </ButtonCore>
                        </td>
                    </tr>
                </tbody>
            </table>
        );
        const tree = renderer.create(example).toJSON();
        expect(tree).toMatchSnapshot();
    });
    it("example 3", () => {
        const Color = require("wonder-blocks-color").default;
        const ButtonCore = require("./components/button-core.js").default;

        const {blue, red, white, offWhite} = Color;

        const example = (
            <table style={{background: offWhite, textAlign: "center"}}>
                <thead>
                    <tr>
                        <th />
                        <th style={{width: 100}}>Default</th>
                        <th style={{width: 100}}>
                            Hovered/<br />Focused
                        </th>
                        <th style={{width: 100}}>
                            Active/<br />Pressed
                        </th>
                        <th style={{width: 100}}>Disabled</th>
                    </tr>
                </thead>
                <tbody>
                    <tr style={{height: 60, verticalAlign: "middle"}}>
                        <th>Primary</th>
                        <td>
                            <ButtonCore
                                kind="primary"
                                size="default"
                                color={red}
                                light={false}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="primary"
                                size="default"
                                color={red}
                                light={false}
                                hovered={true}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="primary"
                                size="default"
                                color={red}
                                light={false}
                                hovered={false}
                                focused={false}
                                pressed={true}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="primary"
                                size="default"
                                color={red}
                                light={false}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={true}
                            >
                                Label
                            </ButtonCore>
                        </td>
                    </tr>
                    <tr style={{height: 60, verticalAlign: "middle"}}>
                        <th>Secondary</th>
                        <td>
                            <ButtonCore
                                kind="secondary"
                                size="default"
                                color={red}
                                light={false}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="secondary"
                                size="default"
                                color={red}
                                light={false}
                                hovered={true}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="secondary"
                                size="default"
                                color={red}
                                light={false}
                                hovered={false}
                                focused={false}
                                pressed={true}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="secondary"
                                size="default"
                                color={red}
                                light={false}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={true}
                            >
                                Label
                            </ButtonCore>
                        </td>
                    </tr>
                    <tr style={{height: 60, verticalAlign: "middle"}}>
                        <th>Tertiary</th>
                        <td>
                            <ButtonCore
                                kind="tertiary"
                                size="default"
                                color={red}
                                light={false}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="tertiary"
                                size="default"
                                color={red}
                                light={false}
                                hovered={true}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="tertiary"
                                size="default"
                                color={red}
                                light={false}
                                hovered={false}
                                focused={false}
                                pressed={true}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="tertiary"
                                size="default"
                                color={red}
                                light={false}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={true}
                            >
                                Label
                            </ButtonCore>
                        </td>
                    </tr>
                </tbody>
            </table>
        );
        const tree = renderer.create(example).toJSON();
        expect(tree).toMatchSnapshot();
    });
    it("example 4", () => {
        const Color = require("wonder-blocks-color").default;
        const ButtonCore = require("./components/button-core.js").default;

        const {blue, red, white, offWhite} = Color;

        const example = (
            <table style={{background: red, color: white, textAlign: "center"}}>
                <thead>
                    <tr>
                        <th />
                        <th style={{width: 100}}>Default</th>
                        <th style={{width: 100}}>
                            Hovered/<br />Focused
                        </th>
                        <th style={{width: 100}}>
                            Active/<br />Pressed
                        </th>
                        <th style={{width: 100}}>Disabled</th>
                    </tr>
                </thead>
                <tbody>
                    <tr style={{height: 60, verticalAlign: "middle"}}>
                        <th>Primary</th>
                        <td>
                            <ButtonCore
                                kind="primary"
                                size="default"
                                color={red}
                                light={true}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="primary"
                                size="default"
                                color={red}
                                light={true}
                                hovered={true}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="primary"
                                size="default"
                                color={red}
                                light={true}
                                hovered={false}
                                focused={false}
                                pressed={true}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="primary"
                                size="default"
                                color={red}
                                light={true}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={true}
                            >
                                Label
                            </ButtonCore>
                        </td>
                    </tr>
                    <tr style={{height: 60, verticalAlign: "middle"}}>
                        <th>Secondary</th>
                        <td>
                            <ButtonCore
                                kind="secondary"
                                size="default"
                                color={red}
                                light={true}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="secondary"
                                size="default"
                                color={red}
                                light={true}
                                hovered={true}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="secondary"
                                size="default"
                                color={red}
                                light={true}
                                hovered={false}
                                focused={false}
                                pressed={true}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="secondary"
                                size="default"
                                color={red}
                                light={true}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={true}
                            >
                                Label
                            </ButtonCore>
                        </td>
                    </tr>
                    <tr style={{height: 60, verticalAlign: "middle"}}>
                        <th>Tertiary</th>
                        <td>
                            <ButtonCore
                                kind="tertiary"
                                size="default"
                                color={red}
                                light={true}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="tertiary"
                                size="default"
                                color={red}
                                light={true}
                                hovered={true}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="tertiary"
                                size="default"
                                color={red}
                                light={true}
                                hovered={false}
                                focused={false}
                                pressed={true}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="tertiary"
                                size="default"
                                color={red}
                                light={true}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={true}
                            >
                                Label
                            </ButtonCore>
                        </td>
                    </tr>
                </tbody>
            </table>
        );
        const tree = renderer.create(example).toJSON();
        expect(tree).toMatchSnapshot();
    });
    it("example 5", () => {
        const Color = require("wonder-blocks-color").default;
        const ButtonCore = require("./components/button-core.js").default;

        const {blue, red, white, offWhite} = Color;

        const example = (
            <table style={{background: offWhite, textAlign: "center"}}>
                <thead>
                    <tr>
                        <th />
                        <th style={{width: 100}}>Default</th>
                        <th style={{width: 100}}>
                            Hovered/<br />Focused
                        </th>
                        <th style={{width: 100}}>
                            Active/<br />Pressed
                        </th>
                        <th style={{width: 100}}>Disabled</th>
                    </tr>
                </thead>
                <tbody>
                    <tr style={{height: 60, verticalAlign: "middle"}}>
                        <th>Primary</th>
                        <td>
                            <ButtonCore
                                kind="primary"
                                size="small"
                                color={blue}
                                light={false}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="primary"
                                size="small"
                                color={blue}
                                light={false}
                                hovered={true}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="primary"
                                size="small"
                                color={blue}
                                light={false}
                                hovered={false}
                                focused={false}
                                pressed={true}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="primary"
                                size="small"
                                color={blue}
                                light={false}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={true}
                            >
                                Label
                            </ButtonCore>
                        </td>
                    </tr>
                    <tr style={{height: 60, verticalAlign: "middle"}}>
                        <th>Secondary</th>
                        <td>
                            <ButtonCore
                                kind="secondary"
                                size="small"
                                color={blue}
                                light={false}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="secondary"
                                size="small"
                                color={blue}
                                light={false}
                                hovered={true}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="secondary"
                                size="small"
                                color={blue}
                                light={false}
                                hovered={false}
                                focused={false}
                                pressed={true}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="secondary"
                                size="small"
                                color={blue}
                                light={false}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={true}
                            >
                                Label
                            </ButtonCore>
                        </td>
                    </tr>
                    <tr style={{height: 60, verticalAlign: "middle"}}>
                        <th>Tertiary</th>
                        <td>
                            <ButtonCore
                                kind="tertiary"
                                size="small"
                                color={blue}
                                light={false}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="tertiary"
                                size="small"
                                color={blue}
                                light={false}
                                hovered={true}
                                focused={false}
                                pressed={false}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="tertiary"
                                size="small"
                                color={blue}
                                light={false}
                                hovered={false}
                                focused={false}
                                pressed={true}
                                disabled={false}
                            >
                                Label
                            </ButtonCore>
                        </td>
                        <td>
                            <ButtonCore
                                kind="tertiary"
                                size="small"
                                color={blue}
                                light={false}
                                hovered={false}
                                focused={false}
                                pressed={false}
                                disabled={true}
                            >
                                Label
                            </ButtonCore>
                        </td>
                    </tr>
                </tbody>
            </table>
        );
        const tree = renderer.create(example).toJSON();
        expect(tree).toMatchSnapshot();
    });
});
