// @flow
// This file is auto-generated by gen-snapshot-tests.js
// Do not edit this file.  To make changes to these snapshot tests:
//   1. edit the markdown documentation files in the package,
//        packages/wonder-blocks-dropdown
//   2. Run `yarn run gen-snapshot-tests`.
import React from "react";
import renderer from "react-test-renderer";
import ActionMenu from "./components/action-menu.js";
import SingleSelectMenu from "./components/single-select-menu.js";
import MultiSelectMenu from "./components/multi-select-menu.js";
import SelectBox from "./components/select-box.js";

describe("wonder-blocks-dropdown", () => {
    it("example 1", () => {
        const {View} = require("@khanacademy/wonder-blocks-core");
        const {StyleSheet} = require("aphrodite");

        const styles = StyleSheet.create({
            row: {
                flexDirection: "row",
            },
            sideMargins: {
                marginRight: 10,
            },
            darkBackgroundWrapper: {
                background: "black",
                padding: 10,
            },
            strutLike: {
                width: 8,
            },
        });
        const example = (
            <View style={[styles.row]}>
                <ActionMenu
                    items={[
                        {
                            type: "action",
                            label: "Action 1",
                            onClick: () => console.log("Trigger action 1"),
                        },
                        {
                            type: "action",
                            label: "Action 2",
                            disabled: true,
                            onClick: () => console.log("Trigger action 2"),
                        },
                        {
                            type: "separator",
                        },
                        {
                            type: "select",
                            label: "Toggle action 1",
                            onClick: (state) =>
                                console.log(`action 1 ${state.toString()}`),
                            selected: false,
                            value: "action 1",
                        },
                        {
                            type: "select",
                            label: "Toggle action",
                            onClick: (state) =>
                                console.log(`action 2 ${state.toString()}`),
                            selected: true,
                            value: "action 2",
                        },
                    ]}
                    menuText={"Action menu"}
                    containsSelectionOptions={true}
                />
                <View style={[styles.strutLike]} />

                <SelectBox
                    light={false}
                    isPlaceholder={false}
                    onClick={() => console.log("hi")}
                >
                    Selecting
                </SelectBox>
                <View style={[styles.strutLike]} />
                <View style={[styles.darkBackgroundWrapper]}>
                    <SelectBox
                        light={true}
                        isPlaceholder={true}
                        onClick={() => console.log("hi")}
                    >
                        Selecting
                    </SelectBox>
                </View>
                <View style={[styles.strutLike]} />
                <SelectBox
                    disabled={true}
                    onClick={() => console.log("error error!!")}
                >
                    Selecting
                </SelectBox>
                <View style={[styles.strutLike]} />

                <MultiSelectMenu
                    alignment={"right"}
                    displaySelectShortcuts={true}
                    items={[
                        {
                            type: "select",
                            label: "Anesu",
                            selected: false,
                            value: "anesu",
                        },
                        {
                            type: "select",
                            label: "Jennie",
                            selected: true,
                            value: "jennie",
                        },
                        {
                            type: "select",
                            label: "Mary",
                            selected: true,
                            value: "mary",
                        },
                        {
                            type: "select",
                            label: "Sophie",
                            selected: false,
                            value: "sophie",
                        },
                    ]}
                    onChange={(s) => console.log(s)}
                    selectItemType={"interns"}
                />
                <View style={[styles.strutLike]} />

                <View style={[styles.darkBackgroundWrapper]}>
                    <SingleSelectMenu
                        items={[
                            {
                                type: "select",
                                label: "Banana",
                                selected: false,
                                value: "banana",
                            },
                            {
                                type: "select",
                                label: "Apple",
                                selected: false,
                                value: "apple",
                            },
                            {
                                type: "select",
                                label: "Grape",
                                selected: false,
                                value: "grape",
                            },
                        ]}
                        light={true}
                        onChange={(s) => console.log(s)}
                        placeholder={"Choose a fruit"}
                    />
                </View>
            </View>
        );

        const tree = renderer.create(example).toJSON();
        expect(tree).toMatchSnapshot();
    });
});
