coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default: on
    patch:
      default: off
    changes:
      default: off

comment:
  layout: "header, reach, diff, flags, files, footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "utils/*.ts"
  - "packages/**/dist/index.js"
  - "package"
  - "packages/**/types.ts"
  - "packages/**/*.typestest.ts"
  - "packages/**/types.js"
  - "packages/**/*.typestest.js"
