language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm run build:all
  - npm install -g codecov
script:
  - npm test
  - npm run coverage && codecov
