language: node_js
node_js:
  - stable
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
  - yarn run build:all
  - cd demo && yarn install && cd ..
  - yarn global add codecov
script:
  - yarn test
  - yarn run coverage && codecov
