language: node_js
node_js:
  - stable
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
  - npm run build:all
  - cd demo && npm install && cd ..
  - npm install -g codecov
script:
  - npm test
  - npm run coverage && codecov
