language: node_js
node_js:
  - stable
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
  - yarn run build:all
  - yarn global add codecov && PATH=$PATH:$(yarn global bin)
script:
  - yarn test:coverage && codecov
