packages:
    # All WB packages
    - "packages/*"
    # Required for building WB packages
    - "build-settings"
    # AST transforms
    - "wb-codemod"
catalog:
    # Babel
    "@babel/runtime": ^7.24.5
    # Wonder Stuff
    "@khanacademy/wonder-stuff-core": ^1.5.4
    # Icons library
    "@phosphor-icons/core": ^2.0.2
    # Positioning
    "@popperjs/core": ^2.10.1
    react-popper: ^2.3.0
    # Styling
    aphrodite: ^1.2.5
    # Dates
    moment: 2.29.4
    # Testing/data
    node-fetch: ^2.6.7
    # React
    "react": 18.2.0
    "react-dom": 18.2.0
    # React Router
    react-router: 6.30.0
    react-router-dom: 6.30.0
    # Virtualization
    react-window: ^1.8.11
