// This file is auto-generated by gen-snapshot-tests.js
// Do not edit this file.  To make changes to these snapshot tests:
//   1. edit the markdown documentation files in the package,
//        packages/wonder-blocks-breadcrumbs
//   2. Run `yarn run gen-snapshot-tests`.
import React from "react";
import renderer from "react-test-renderer";

// Mock react-dom as jest doesn't like findDOMNode.
jest.mock("react-dom");
import Breadcrumbs from "./components/breadcrumbs.js";
import BreadcrumbsItem from "./components/breadcrumbs-item.js";

describe("wonder-blocks-breadcrumbs", () => {
    it("example 1", () => {
        const Link = require("@khanacademy/wonder-blocks-link").default;
        const {
            Breadcrumbs,
            BreadcrumbsItem,
        } = require("@khanacademy/wonder-blocks-breadcrumbs");

        const example = (
            <Breadcrumbs>
                <BreadcrumbsItem>
                    <Link href="https://khanacademy.org/">Home</Link>
                </BreadcrumbsItem>
                <BreadcrumbsItem>
                    <Link href="https://khanacademy.org/about">About</Link>
                </BreadcrumbsItem>
                <BreadcrumbsItem>Current page</BreadcrumbsItem>
            </Breadcrumbs>
        );
        const tree = renderer.create(example).toJSON();
        expect(tree).toMatchSnapshot();
    });
});
