// This file is auto-generated by gen-snapshot-tests.js
// Do not edit this file.  To make changes to these snapshot tests:
//   1. edit the markdown documentation files in the package,
//        packages/wonder-blocks-breadcrumbs
//   2. Run `yarn run gen-snapshot-tests`.
import React from "react";
import renderer from "react-test-renderer";

// Mock react-dom as jest doesn't like findDOMNode.
jest.mock("react-dom");
import Link from "@khanacademy/wonder-blocks-link";
import {
    Breadcrumbs,
    BreadcrumbsItem,
} from "@khanacademy/wonder-blocks-breadcrumbs";

describe("wonder-blocks-breadcrumbs", () => {
    it("example 1", () => {
        const example = (
            <Breadcrumbs>
                <BreadcrumbsItem>
                    <Link href="https://khanacademy.org/">Home</Link>
                </BreadcrumbsItem>
                <BreadcrumbsItem>
                    <Link href="https://khanacademy.org/about">About</Link>
                </BreadcrumbsItem>
                <BreadcrumbsItem>Current page</BreadcrumbsItem>
            </Breadcrumbs>
        );
        const tree = renderer.create(example).toJSON();
        expect(tree).toMatchSnapshot();
    });
});
