import React from "react"
import { ActivityIconButton } from "../activity-icon-button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ActivityIconButton,
  "https://www.figma.com/design/EuFu0U7gqc1koXm8ZhlOLp/%E2%9A%A1%EF%B8%8F-Components?node-id=6072%3A1968",
  {
    props: {
      hierarchy: figma.enum("Hierarchy", {
        Primary: "primary",
        Tertiary: "tertiary",
        Secondary: "secondary",
      }),
      state: figma.enum("State", {
        Rest: "rest",
        Hover: "hover",
        Press: "press",
        Selected: "selected",
      }),
      visibleLabel: figma.boolean("Visible Label"),
      focus: figma.boolean("Focus"),
    },
    example: (props) => <ActivityIconButton />,
  },
)
