import tokens from "./tokens";

export const theme = {
    border: {
        radius: {
            xSmall: 2,
            small: 3,
            medium: 4,
            large: 6,
            full: "50%",
        },
        width: {
            none: 0,
            small: 1,
            medium: 2,
            large: 4,
        },
    },
    color: {
        bg: {
            action: tokens.colors.blue,
            actionActive: tokens.colors.activeBlue,
            actionInverse: tokens.colors.fadedBlue,
            critical: tokens.colors.red,
            criticalActive: tokens.colors.activeRed,
            criticalInverse: tokens.colors.fadedRed,
            accent: tokens.colors.gold,
            mastery: tokens.colors.purple,
            success: tokens.colors.green,
            primary: tokens.colors.white,
            primaryDisabled: tokens.colors.offBlack32,
            primaryHover: tokens.colors.offBlack8,
            primaryPressed: tokens.colors.offBlack16,
            secondary: tokens.colors.offBlack64,
            secondaryDisabled: tokens.colors.offWhite,
            inverse: tokens.colors.darkBlue,
        },
        text: {
            action: tokens.colors.blue,
            actionActive: tokens.colors.activeBlue,
            actionInverse: tokens.colors.fadedBlue,
            critical: tokens.colors.red,
            criticalActive: tokens.colors.activeRed,
            criticalInverse: tokens.colors.fadedRed,
            disabled: tokens.colors.offBlack32,
            primary: tokens.colors.offBlack,
            primaryInverse: tokens.colors.white,
            secondary: tokens.colors.offBlack64,
            secondaryInverse: tokens.colors.white50,
            tertiaryInverse: tokens.colors.white64,
        },
        border: {
            action: tokens.colors.blue,
            actionActive: tokens.colors.activeBlue,
            actionInverse: tokens.colors.fadedBlue,
            critical: tokens.colors.red,
            criticalActive: tokens.colors.activeRed,
            criticalInverse: tokens.colors.fadedRed,
            disabled: tokens.colors.offBlack32,
            primary: tokens.colors.offBlack16,
            primaryInverseFocus: tokens.colors.white,
            secondary: tokens.colors.offBlack50,
            secondaryInverse: tokens.colors.white50,
        },
    },
    spacing: tokens.spacing,
    fontSize: {
        small: `${tokens.fontSizes.xSmall}px`,
        medium: `${tokens.fontSizes.medium}px`,
        large: `${tokens.fontSizes.xLarge}px`,
    },
    font: tokens.fonts,
    fontWeight: tokens.fontWeights,
    lineHeight: {
        small: `${tokens.lineHeights.small}px`,
        medium: `${tokens.lineHeights.medium}px`,
        large: `${tokens.lineHeights.large}px`,
    },
};

export default theme;
