version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "yarn.lock" }}
            - npm-deps-
      - run: yarn install
      - save_cache:
          key: npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn run lint
      - run: yarn run flow
  test:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "yarn.lock" }}
            - npm-deps-
      - run: yarn install
      - save_cache:
          key: npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn run gen-snapshot-tests
      - run: yarn run build:cjs
      - run: yarn run build:es6
      - run: yarn run jest --coverage
      - run: yarn run codecov
  screenshots:
    machine: true
    steps:
      - run: sudo curl -sL https://deb.nodesource.com/setup_8.x | bash
      - run: sudo apt-get install -y nodejs
      - run: sudo npm i -g yarn
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "yarn.lock" }}
            - npm-deps-
      - run: yarn install
      - save_cache:
          key: npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn screenshots
      - store_artifacts:
          path: screenshots
          destination: screenshots
workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint
      - test
      - screenshots
