version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: yarn install
      - run: yarn run lint
      - run: yarn run flow
  test:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: yarn install
      - run: yarn run gen-snapshot-tests
      - run: yarn run build:all
      - run: yarn run jest --coverage
      - run: yarn add codecov
      - run: yarn run codecov
workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint
      - test
