version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "yarn.lock" }}
            - npm-deps-
      - run: yarn install
      - save_cache:
          key: npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn run lint
      - run: yarn run flow
  test:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "yarn.lock" }}
            - npm-deps-
      - run: yarn install
      - save_cache:
          key: npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn run gen-snapshot-tests
      - run: yarn run build:all
      - run: yarn run jest --coverage
      - run: yarn run codecov
workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint
      - test
