version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "yarn.lock" }}
            - npm-deps-
      - run: yarn install
      - save_cache:
          key: npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn run lint
      - run: yarn run flow
  test:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "yarn.lock" }}
            - npm-deps-
      - run: yarn install
      - save_cache:
          key: npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn run gen-snapshot-tests
      - run: yarn run build:cjs
      - run: yarn run build:es6
      - run: yarn run jest --coverage
      - run: yarn run codecov
  screenshots:
    docker:
      - image: kevinbarabash/vite
    steps:
      - setup_remote_docker
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "yarn.lock" }}
            - npm-deps-
      - run: yarn install
      - save_cache:
          key: npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: vite sh /home/vite/docker/commands.sh
      - store_artifacts:
          path: screenshots
          destination: screenshots
workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint
      - test
      - screenshots
