version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "yarn.lock" }}
            - npm-deps-
      - run: yarn install
      - save_cache:
          key: npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn run build:cjs
      - run: yarn run lint
      - run: yarn run flow-ci
  test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "yarn.lock" }}
            - npm-deps-
      - run: yarn install
      - save_cache:
          key: npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn run gen-snapshot-tests
      - run: yarn run build:cjs
      - run: yarn run build:es6
      # --runInBand forces tests to be run in the main process.
      # This is useful for debugging or in this case only using
      # a single process.  This prevents ENOMEM when running on
      # circleci.
      - run: yarn run jest --coverage --runInBand
      - run: yarn run codecov
workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint
      - test
