// This file is auto-generated by gen-snapshot-tests.js
// Do not edit this file.  To make changes to these snapshot tests
// edit packages/wonder-blocks-modal/docs.md and run `npm run gen-snapshot-tests`.
import React from "react";
import renderer from "react-test-renderer";
import TwoColumnModal from "./components/two-column-modal.js";

describe("wonder-blocks-modal", () => {
    it("example 1", () => {
        const TwoColumnModal = require("./components/two-column-modal.js").default;
        
        const example = <TwoColumnModal />
        const tree = renderer.create(example).toJSON();
        expect(tree).toMatchSnapshot();
    });
});
