import React from "react";
import figma from "@figma/code-connect";
import Accordion from "../accordion";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Accordion,
    "https://www.figma.com/design/EuFu0U7gqc1koXm8ZhlOLp/%E2%9A%A1%EF%B8%8F-Components?node-id=10108%3A12032",
    {
        props: {
            cornerStyle: figma.enum("Corner Style", {
                Default: "default",
                "All Round": "all-round",
                "Top Round": "top-round",
                "Bottom Round": "bottom-round",
            }),
            expanded: figma.boolean("Expanded"),
            children: figma.children("*"),
        },
        example: (props: any) => (
            <Accordion {...props}>{props.children}</Accordion>
        ),
    },
);
