// This file is auto-generated by gen-snapshot-tests.js
// Do not edit this file.  To make changes to these snapshot tests:
//   1. edit the markdown documentation files in the package,
//        packages/wonder-blocks-icon-button
//   2. Run `yarn run gen-snapshot-tests`.
import React from "react";
import renderer from "react-test-renderer";

// Mock react-dom as jest doesn't like findDOMNode.
jest.mock("react-dom");
import IconButton from "./components/icon-button.js";

describe("wonder-blocks-icon-button", () => {
    it("example 1", () => {
        const {View} = require("@khanacademy/wonder-blocks-core");
        const {icons} = require("@khanacademy/wonder-blocks-icon");
        const {StyleSheet} = require("aphrodite");

        const styles = StyleSheet.create({
            row: {
                flexDirection: "row",
            },
            sideMargins: {
                marginRight: 10,
            },
        });

        const example = (
            <View style={[styles.row]}>
                <IconButton
                    icon={icons.search}
                    aria-label="search"
                    onClick={(e) => console.log("hello")}
                    style={[styles.sideMargins]}
                />
                <IconButton
                    icon={icons.search}
                    aria-label="search"
                    kind="secondary"
                    onClick={(e) => console.log("hello")}
                    style={[styles.sideMargins]}
                />
                <IconButton
                    icon={icons.search}
                    aria-label="search"
                    kind="tertiary"
                    onClick={(e) => console.log("hello")}
                    style={[styles.sideMargins]}
                />
            </View>
        );

        const tree = renderer.create(example).toJSON();
        expect(tree).toMatchSnapshot();
    });
});
