import * as React from "react";
import ModalFooter from "../modal-footer";
import {figma} from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
    ModalFooter,
    "https://www.figma.com/design/EuFu0U7gqc1koXm8ZhlOLp/%E2%9A%A1%EF%B8%8F-Components?node-id=2215%3A445",
    {
        props: {
            // No matching props could be found for these Figma properties:
            // "action1": figma.boolean('Action 1'),
            // "action2": figma.boolean('Action 2'),
            // "action3": figma.boolean('Action 3'),
            // "writingDirection": figma.enum('Writing Direction', {
            //   "Left-to-Right": "left-to-right",
            //   "Right-to-Left": "right-to-left"
            // })
        },
        example: (props) => <ModalFooter />,
    },
);
