import figma from "@figma/code-connect";
import React from "react";

import Radio from "../radio";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Radio,
    "https://www.figma.com/design/EuFu0U7gqc1koXm8ZhlOLp/%E2%9A%A1%EF%B8%8F-Components?node-id=9602%3A8600",
    {
        props: {
            writingDirection: figma.enum("Writing Direction", {
                "Left-to-Right": "left-to-right",
                "Right-to-Left": "right-to-left",
            }),
        },
        example: (props) => <Radio />,
    },
);
