name: 'Shared Node Cache'
description: 'Install & cache our JavaScript dependencies'
inputs:
  node-version:
    description: 'Node version to use'
    required: false
    default: '16.x'
runs:
  using: "composite"
  steps:

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.node-version }}

    - uses: actions/cache@v2
      id: node-modules-cache # use this to check for `cache-hit` (`steps.node-modules-cache.outputs.cache-hit != 'true'`)
      with:
        path: node_modules
        key: ${{ runner.os }}${{ inputs.node-version }}-node-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}${{ inputs.node-version }}-node-modules-

    - name: Install dependencies
      shell: bash
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile