name: 'Shared Node Cache'
description: 'Install & cache our npm dependencies'

# The inputs this action expects.
inputs:
  node-version:
    description: 'Node version to use'
    required: false
    default: '>=24.18 <25'
  cache-bust:
    description: 'A unique string to bust the cache'
    required: true

# The steps this action runs.
runs:
  using: "composite"
  steps:

    - uses: pnpm/action-setup@v5
      name: Install pnpm
      with:
        run_install: false

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
        cache-dependency-path: 'pnpm-lock.yaml'

    - name: ⬆️ Upgrade npm for OIDC support
      shell: bash
      run: |
          # npm trusted publishing requires npm CLI v11.5.1+, but NOT
          # the new v12, which is broken when detecting which packages
          # need to be published!
          #
          # We force the install here to be sure we're on npm 11
          npm install -g npm@11
          echo "✅ npm upgraded to $(npm --version)"

    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
