name: Chromatic - Release PR opened

on:
  pull_request:
    types:
      - opened

jobs:
  chromatic:
    # Only run this workflow when the Release PR is opened/created.
    if: startsWith(github.head_ref, 'changeset-release/')
    uses: ./.github/workflows/chromatic-build.yml
    with:
      target: "release"
