name: Chromatic - Push

on: push

jobs:

  # ------- Dependabot PRs --------
  chromatic_dependabot:
    # (else) Run this step on dependabot PRs.
    if: github.actor == 'dependabot[bot]'
    name: Chromatic - Skip on dependabot PRs (push)
    uses: ./.github/workflows/chromatic-build.yml
    with:
      target: 'bot'
    secrets:
      projectToken: ${{ secrets.CHROMATIC_APP_CODE }}
