name: Chromatic - Release PR

on:
  pull_request:
    types:
      - opened

jobs:
  chromatic:
    runs-on: ${{ matrix.os }}
    env:
      CI: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
    # Only run this workflow when the Release PR is opened/created.
    if: startsWith(github.head_ref, 'changeset-release/')
    steps:
    - name: Install and build
      uses: Khan/wonder-blocks/.github/workflows/chromatic-build.yml@main

    - name: Publish to Chromatic for visual testing
      if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
      uses: chromaui/action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        projectToken: ${{ secrets.CHROMATIC_APP_CODE }}
        autoAcceptChanges: true
