name: Chromatic - Push

on: push

jobs:
  chromatic:
    # (if) Run this step on non-dependabot PRs.
    if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
    uses: ./.github/workflows/chromatic-build.yml
    with:
      target: 'review'

    # (else) Run this step on dependabot PRs.
    if: github.actor == 'dependabot[bot]'
    uses: ./.github/workflows/chromatic-build.yml
    with:
      target: 'dependabot'