name: Chromatic

on: push

jobs:
  chromatic:
    runs-on: ${{ matrix.os }}
    env:
      CI: true
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [14]
    steps:
    - name: Checking out latest commit
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache node modules and install dependencies
      uses: Khan/wonder-blocks/.github/workflows/node-modules.yml
      with:
        os: ${{ matrix.os }}
        key: ${{ runner.os }}-${{ matrix.node-version }}

    - name: yarn build:all
      run: yarn build:all
    # (if) Run this step on non-dependabot PRs.
    - name: Publish to Chromatic for visual testing
      if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
      uses: chromaui/action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        projectToken: ${{ secrets.CHROMATIC_APP_CODE }}
        autoAcceptChanges: "master"
    # (else) Run this step on dependabot PRs.
    - name: Skip Chromatic builds
      if: ${{ github.actor == 'dependabot[bot]' }}
      uses: chromaui/action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        projectToken: ${{ secrets.CHROMATIC_APP_CODE }}
        exitZeroOnChanges: true
        # This is a flag that allows us to skip the build in the case of a
        # dependabot PR. We still need to report the build as successful so that
        # the checks are valid and Dependabot can continue.
        skip: true
