name: Chromatic - Push

on: push

jobs:
  chromatic:
    runs-on: ${{ matrix.os }}
    uses: Khan/wonder-blocks/.github/workflows/chromatic-build.yml@main
    env:
      CI: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
    steps:
    # (if) Run this step on non-dependabot PRs.
    - name: Publish to Chromatic for visual testing
      if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
      uses: chromaui/action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        projectToken: ${{ secrets.CHROMATIC_APP_CODE }}
        autoAcceptChanges: "main"
    # (else) Run this step on dependabot PRs.
    - name: Skip Chromatic builds
      if: ${{ github.actor == 'dependabot[bot]' }}
      uses: chromaui/action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        projectToken: ${{ secrets.CHROMATIC_APP_CODE }}
        exitZeroOnChanges: true
        # This is a flag that allows us to skip the build in the case of a
        # dependabot PR. We still need to report the build as successful so that
        # the checks are valid and Dependabot can continue.
        skip: true
