# This reusable workflow is executed to run test checks for the project
name: Run tests for the project

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [24.x]
        shard: ["1/2", "2/2"]
    steps:
      - uses: actions/checkout@v5
      - name: Secure Network
        uses: Khan/actions@secure-network-v1
        timeout-minutes: 5
        with:
            # registry.npmjs.org: npm package registry for pnpm install
            # codecov.io: upload coverage reports
            extra-domains: registry.npmjs.org codecov.io
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install & cache node_modules
        uses: ./.github/actions/shared-node-cache
        with:
          node-version: ${{ matrix.node-version }}
      # Testing and coverage
      - name: Run jest tests with coverage
        run: pnpm coverage:ci --shard ${{ matrix.shard }}
      - name: Upload Coverage
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/coverage-final.json
