# This reusable workflow is executed to run linting checks for the project
name: Run lint for the project

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install & cache node_modules
        uses: ./.github/actions/shared-node-cache
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get All Changed Files
        uses: Khan/actions@get-changed-files-v2
        id: changed

      - id: js-ts-files
        name: Find .js, .ts changed files
        uses: Khan/actions@filter-files-v1
        with:
          changed-files: ${{ steps.changed.outputs.files }}
          extensions: '.js,.jsx,.ts,.tsx'

      - id: eslint-reset
        uses: Khan/actions@filter-files-v1
        name: Files that would trigger a full eslint run
        with:
          changed-files: ${{ steps.changed.outputs.files }}
          files: '.eslintrc.js,pnpm-lock.yaml,.eslintignore'

      - id: typecheck-reset
        uses: Khan/actions@filter-files-v1
        name: Files that would trigger a typecheck run
        with:
          changed-files: ${{ steps.changed.outputs.files }}
          files: '.pnpm-lock.yaml'

      # Linting / type checking
      - name: Eslint
        uses: Khan/actions@full-or-limited-v0
        with:
          full-trigger: ${{ steps.eslint-reset.outputs.filtered }}
          full: pnpm lint:ci .
          limited-trigger: ${{ steps.js-ts-files.outputs.filtered }}
          limited: pnpm lint:ci {}

      - name: Typecheck
        if: always() # always run this check until we update the eslint config
        # if: steps.js-ts-files.outputs.filtered != '[]' || steps.typecheck-reset.outputs.filtered != '[]'
        run: pnpm typecheck

      - name: Build .js bundles
        run: pnpm build

      - name: Build .d.ts types
        run: pnpm build:types

      - name: Check package.json files
        run: ./utils/publish/pre-publish-check-ci.ts
